create table client(
                       id int generated by default as identity primary key,
                       name varchar unique not null,
                       surname varchar unique not null,
                       profession varchar not null ,
                       register_at timestamp not null
);

create table address(
                        id int generated by default as identity primary key,
                        street varchar not null unique,
                        street_number int not null,
                        client int references client(id)
);